Repository knaxus/native-javascript, pull requests merged in 2019-10, with the labels that each got.

#3 add support for eslint (closes #1)
  .eslintrc
  .gitignore
  forEach.js
  package.json
Labels: beginner friendly, enhancement, hacktoberfest

#11 toUpperCase implemented
  implementations/toUpperCase.js
Labels: beginner friendly, changes required, hacktoberfest, under review

#7 toLowerCase implemented
  implementations/toLowerCase.js
Labels: beginner friendly, hacktoberfest, under review

#15 Implemented Array.map method #hacktoberfest
  implementations/map.js
Labels: beginner friendly, hacktoberfest, under review

#17 Add Array.prototype.filter implementation
  implementations/filter.js
Labels: beginner friendly, good first issue, hacktoberfest, under review

#24 Add Array.prototype.flatMap() implementation
  implementations/flatMap.js
Labels: beginner friendly, good first issue, hacktoberfest, review done

#19 Add implementation of Array.prototype.reduce
  implementations/reduce.js
Labels: beginner friendly, hacktoberfest, review done
